### ISSUE TITLE
Children component routes

### ISSUE THREAD

**Issue by francesco-strazzullo** [AngularClass/webpack-toolkit#4]
Hi Guys,
can you add in the README how to add async routes with children?

**Comment by PatrickJS** [comment]
this can be done but it's also a little bit tricky for configuration

**Comment by francesco-strazzullo** [comment]
Ok, can you write here an example?

**Comment by PatrickJS** [comment]
I created a helper and wrote an example https://github.com/AngularClass/angular2-webpack-starter/compare/ac32c4b51f52d3ba76670a3020fb7428d2590d8c...master

**Comment by francesco-strazzullo** [comment]
@gdi2290 the code doesn't work with the new @angular/router 3.0.0-alpha.8

**Comment by PatrickJS** [comment]
it works for me. what version of node, npm, angular, which os, and browser?

**Comment by francesco-strazzullo** [comment]
Node 6, Angular 2.rc3, Chrome. I have a strange behavior: I need to click twice on the links to make it work. On the first time the bundle it's downloaded but nothing happens. On the second time everything works as usual. I will look into it.

**Comment by PatrickJS** [comment]
can you implement this work around https://github.com/AngularClass/angular2-webpack-starter/commit/d4ecb3f2214e8725e708c65b6c1d503e4b311ce4

**Comment by francesco-strazzullo** [comment]
Ok I will try and let you know!

**Comment by francesco-strazzullo** [comment]
It works with alpha8 now, thanks @gdi2290

**Comment by PatrickJS** [comment]
kool, you should update to 3.0.0-beta.2

**Comment by francesco-strazzullo** [comment]
Already done yesterday and it's still working!
